QueryManager/core/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static


urlpatterns = [
    path('QueryManager/admin/', admin.site.urls),
    path('',include('main.urls')),
    path('QueryManager/accounts/',include('django.contrib.auth.urls')),
    re_path(r'^QueryManager/media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^QueryManager/static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

QueryManager/main/urls.py
from django.urls import path
from django.contrib import admin
#from django.conf import settings
from django.conf.urls.static import static
#from django.contrib.auth import views as auth_views
from . import views
from .views import (
    home, search_suggestions, tag_suggestions, edit_query,
    mark_as_solution, edit_answer, remove_attachment,
    edit_comment, remove_comment_attachment, remove_question_attachment
)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('QueryManager/', views.home, name='home'),
    path('QueryManager/detail/<int:id>/', views.detail, name='detail'),
    path('QueryManager/save-comment', views.save_comment, name='save-comment'),
    path('QueryManager/save-upvote', views.save_upvote, name='save-upvote'),
    path('QueryManager/save-downvote', views.save_downvote, name='save-downvote'),
    # User Register
    path('QueryManager/accounts/register/', views.register, name='register'),
    # Profile
    path('QueryManager/accounts/profile/', views.profile, name='profile'),
    # Search Suggestions
    path('search_suggestions/', search_suggestions, name='search_suggestions'),
    # Tags Suggestions changes 18/2/25
    path('tag_suggestions/', tag_suggestions, name='tag_suggestions'),
    # Tag Page
    path('QueryManager/tag/<slug:tag>/', views.tag, name='tag'), 
    # Tags Page
    path('QueryManager/tags/', views.tags, name='tags'), 
    # Logout
    path('QueryManager/accounts/logout/', views.custom_logout, name='logout'),
    # Update status
    path('update-status/<int:quest_id>/', views.update_status, name='update-status'),
    # Delete Question
    path('QueryManager/delete-question/<int:question_id>/', views.delete_question, name='delete-question'),
    # Delete Answer
    path('QueryManager/delete-answer/<int:answer_id>/', views.delete_answer, name='delete-answer'),
    # Delete Comment
    path('QueryManager/delete-comment/<int:comment_id>/', views.delete_comment, name='delete-comment'),
    # Mark as solution 21/2/25
    path('mark-as-solution/<int:answer_id>/', mark_as_solution, name='mark-as-solution'),
    # Edit answer 21/2/25
    path('edit_answer/<int:answer_id>/', edit_answer, name='edit_answer'),
    # Remove Answer attachment 21/2/25
    path('remove-attachment/<int:attachment_id>/', remove_attachment, name='remove_attachment'),
    # Edit Comment 21/2/25
    path('edit-comment/<int:comment_id>/', edit_comment, name='edit_comment'),
    # Remove Comment attachment 21/2/25
    path('remove-comment-attachment/<int:attachment_id>/', remove_comment_attachment, name='remove_comment_attachment'),
    # Edit Query 24/2/25
    path("edit/<int:quest_id>/", edit_query, name="edit_query"),
    # Remove Question attachment 24/2/25
    path('remove-question-attachment/<int:attachment_id>/', remove_question_attachment, name='remove_question_attachment'),
    # Help
    path('QueryManager/help/', views.help, name='help'),
    #path('QueryManager/accounts/password-reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    #path('QueryManager/accounts/password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='main/password_reset_done.html'), name='password_reset_done'),
    #path('QueryManager/accounts/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='main/password_reset_confirm.html'), name='password_reset_confirm'),
    #path('QueryManager/accounts/password-reset-complete', auth_views.PasswordResetCompleteView.as_view(template_name='main/password_reset_complete.html'), name='password_reset_complete'),
]

#+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
#   static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

QueryManager/main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from taggit.managers import TaggableManager
from simple_history.models import HistoricalRecords

# Custom User Model
class CustomUser(AbstractUser):
    region = models.CharField(max_length=200)
    email = models.EmailField(blank=False, null=False)
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True, null=True)
    history = HistoricalRecords()

# Question Model
class Question(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    category = models.CharField(max_length=50, blank=True, null=True) #Changes 14/2/2025
    issue = models.CharField(max_length=300)
    detail = models.TextField()
    status = models.BooleanField(default=False)
    referenceform = models.TextField(blank=True) #Changes
    tags = TaggableManager(blank=True) #Changes
    add_time = models.DateTimeField(auto_now_add=True)
    history = HistoricalRecords()
    def __str__(self):
        return self.issue

# Answer Model
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    solution = models.TextField(default='')
    mark_solution = models.BooleanField(default=False) #Changes
    attachment = models.FileField(upload_to='attachments/', blank=True, null=True)
    add_time = models.DateTimeField(auto_now_add=True)
    history = HistoricalRecords()
    def __str__(self):
        return self.solution

# Comment
class Comment(models.Model):
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='comment_user')
    comment = models.TextField(default='')
    add_time = models.DateTimeField(auto_now_add=True)
    history = HistoricalRecords()
    def __str__(self):
        return self.comment

# Attachment Model
class QuestionAttachment(models.Model):
    question = models.ForeignKey(Question, related_name='attachments', on_delete=models.CASCADE)
    file = models.FileField(upload_to='attachments/')

    def is_image(self):
        return self.file.url.lower().endswith(('.png', '.jpg', '.jpeg', '.gif'))
    
class AnswerAttachment(models.Model):
    answer = models.ForeignKey(Answer, related_name='attachments', on_delete=models.CASCADE)
    file = models.FileField(upload_to='attachments/')

    def is_image(self):
        return self.file.url.lower().endswith(('.png', '.jpg', '.jpeg', '.gif'))

class CommentAttachment(models.Model):
    comment = models.ForeignKey(Comment, related_name='attachments', on_delete=models.CASCADE)
    file = models.FileField(upload_to='attachments/')

    def is_image(self):
        return self.file.url.lower().endswith(('.png', '.jpg', '.jpeg', '.gif'))

# UpVotes
class UpVote(models.Model):
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='upvote_user')

# DownVotes
class DownVote(models.Model):
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='downvote_user')

QueryManager/main/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.http import JsonResponse
from .models import Question, Answer, Comment, UpVote, DownVote, QuestionAttachment, AnswerAttachment, CommentAttachment, CustomUser
from django.core.paginator import Paginator
from django.contrib import messages
from .forms import AnswerForm, QuestionForm, ProfileForm, CustomUserCreationForm, CommentForm
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.views.decorators.http import require_http_methods
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.db.models import Count, Prefetch
from django.utils import timezone
from django.template.defaultfilters import slugify
from taggit.models import Tag
from django.http import Http404
from django.core.mail import send_mail, EmailMultiAlternatives
from django.conf import settings
from django.urls import reverse

# Logout
def custom_logout(request):
    logout(request)
    return redirect(settings.LOGIN_URL)
# Question Filter
def get_filtered_questions(q, status_filter, tag_filter, category_filter):
    """Helper function to filter questions based on search and filters."""
    queryset = Question.objects.all().annotate(total_comments=Count('answer__comment')).filter(issue__icontains=q)
    
    if status_filter == 'resolved':
        queryset = queryset.filter(status=True)
    elif status_filter == 'unresolved':
        queryset = queryset.filter(status=False)
    # Automated
    if category_filter == 'HotDocs':
        queryset = queryset.filter(category="HotDocs")
    elif category_filter == 'Document Drafter':
        queryset = queryset.filter(category="Document Drafter")
    # Major works
    elif category_filter == 'Formatting':
        queryset = queryset.filter(category="Formatting")
    elif category_filter == 'Editing':
        queryset = queryset.filter(category="Editing")
    elif category_filter == 'Conversion':
        queryset = queryset.filter(category="Conversion")

    if tag_filter:
        queryset = queryset.filter(tags__name__in=[tag_filter])

    # Prefetch related tags and attachments in a single query to reduce database hits.
    queryset = queryset.prefetch_related('tags', Prefetch('attachments', queryset=QuestionAttachment.objects.all().order_by('-id')))
    
    return queryset.order_by('-id')

def reverse_attachments_for_questions(quests):
    """Helper function to reverse attachments for each question."""
    for quest in quests:
        quest.attachments_reversed = quest.attachments.all()

def handle_question_submission(request):
    """Helper function to handle POST requests for new questions."""
    form = QuestionForm(request.POST)
    if form.is_valid():
        question = form.save(commit=False)
        question.user = request.user
        question.save()

        attachments = [
            QuestionAttachment(question=question, file=file) 
            for file in request.FILES.getlist('attachments')
        ]
        QuestionAttachment.objects.bulk_create(attachments)
        
        form.save_m2m()  # Save tags
        messages.success(request, "Your query has been posted.")
        send_notification_email(question)
        return redirect('home')
    else:
        messages.error(request, 'Please fill in all the required fields correctly.')
        return form

def send_notification_email(question):
    # Generate the full URL
    detail_url = f"{settings.SITE_URL}{reverse('detail', args=[question.id])}"
    
    subject = 'New Query Submitted'
    
    # Plain text message (fallback for email clients that do not support HTML)
    text_message = (
        f"Hello,"
        f"This is a notification to inform you that a new query has been posted on our platform by {question.user.username}.\n\n"
        f"Issue: {question.issue}\n"
        f"Detail: {question.detail}\n"
        f"You can view the query by clicking the link below:\n"
        f"View the question: {detail_url}\n\n"
        f"Please note: This email is for notification purposes only. Replies to this email address are not monitored, and you will not receive a response. "
        f"For further actions or to engage with the query, kindly visit our platform."
        f"Thank you,"
        f"Query Manager"
    )

    # HTML message
    html_message = (
        f"<p>Hello,</p>"
        f"<p>This is a notification to inform you that a new query has been posted on our platform by <strong>{question.user.username}</strong>.</p>"
        f"<p><strong>Issue:</strong> {question.issue}</p>"
        f"<p><strong>Detail:</strong> {question.detail}</p>"
        f"<p>You can view the query by clicking the link below:</p>"
        f"<p><a href='{detail_url}' target='_blank'>View Query</a></p>"
        f"<p><em>Please note:</em> This email is for notification purposes only. Replies to this email address are not monitored, and you will not receive a response.</p>"
        f"<p>For further actions or to engage with the query, kindly visit our platform.</p>"
        f"<p>Thank you,</p>"
        f"<p>Query Manager</p>"
    )
    
    # Get all user emails from the CustomUser model
    user_emails = CustomUser.objects.values_list('email', flat=True)

    # Send the email
    email = EmailMultiAlternatives(
        subject=subject,
        body=text_message,
        from_email=settings.DEFAULT_FROM_EMAIL,
        to=user_emails
    )
    
    # Attach the HTML message as an alternative
    email.attach_alternative(html_message, "text/html")
    email.send()

@login_required
def home(request):
    # Get search and filters
    q = request.GET.get('q', '').strip()
    status_filter = request.GET.get('status', 'all')
    tag_filter = request.GET.get('tag', None)
    category_filter = request.GET.get('category', 'all')

    # Get filtered questions
    quests = get_filtered_questions(q, status_filter, tag_filter, category_filter)

    # Reverse attachments for each quest
    reverse_attachments_for_questions(quests)

    # Check if no results
    no_results = not quests.exists()

    # Handle POST request for new questions
    if request.method == 'POST':
        form = handle_question_submission(request)
        if isinstance(form, QuestionForm):
            return render(request, 'home.html', {'form': form, 'quests': quests, 'tag_filter': tag_filter, 'no_results': no_results})
        return redirect('home')

    else:
        form = QuestionForm()

    # Pagination
    paginator = Paginator(quests, 5)
    page_num = request.GET.get('page', 1)
    quests = paginator.page(page_num)

    # Check if the request is an AJAX request
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return render(request, 'question_list.html', {'quests': quests})

    return render(request, 'home.html', {'form': form, 'quests': quests, 'tag_filter': tag_filter, 'no_results': no_results})

# Search
def search_suggestions(request):
    query = request.GET.get('q', '')
    suggestions = []

    if query:
        questions = Question.objects.filter(issue__icontains=query)[:5]
        for question in questions:
            suggestions.append(question.issue)

        details = Question.objects.filter(detail__icontains=query)[:5]
        for detail in details:
            suggestions.append(detail.detail)

        referenceforms = Question.objects.filter(referenceform__icontains=query)[:5]
        for referenceform in referenceforms:
            suggestions.append(referenceform.referenceform)

        tags = Question.objects.filter(tags__name__icontains=query)[:5]
        for question in tags:
            for tag in question.tags.all():
                suggestions.append(tag.name)

    return JsonResponse(suggestions, safe=False)

# Tag Suggestions 18/2/25
def tag_suggestions(request):
    query = request.GET.get('q', '')
    suggestions = []

    if query:
        tags = Tag.objects.filter(name__icontains=query).values_list('name', flat=True)[:5]
        suggestions = list(tags)

    return JsonResponse(suggestions, safe=False)

# Detail
def detail(request, id):
    quest = get_object_or_404(Question, pk=id)
    tags = quest.tags.all()
    answers = Answer.objects.filter(question=quest).order_by('-add_time')
    answerform = AnswerForm()

    # Get all attachments for the question and answers
    quest.attachments_reversed = quest.attachments.all().order_by('-id')
    for answer in answers:
        answer.attachments_reversed = answer.attachments.all().order_by('-id')

    # Handle POST request for submitting answer
    if request.method == 'POST':
            answerform = AnswerForm(request.POST, request.FILES)
            if answerform.is_valid():
                answer = answerform.save(commit=False)
                answer.question = quest
                answer.user = request.user
                answer.save()

                # Save attachments
                attachments = request.FILES.getlist('attachments')
                for file in attachments:
                    AnswerAttachment.objects.create(answer=answer, file=file)

                messages.success(request, 'Answer has been submitted.')
                return redirect('detail', id=id)
            else:
                messages.error(request, 'Failed to submit the answer.')

    return render(request, 'detail.html', {
        'quest': quest,
        'tags': tags,
        'answers': answers,
        'answerform': answerform
    })

# Update Status
@login_required
def update_status(request, quest_id):
    quest = get_object_or_404(Question, pk=quest_id)
    if request.method == 'POST':
        if request.user == quest.user or request.user.is_superuser:
            status = request.POST.get('status')
            quest.status = bool(int(status))
            quest.save()
            messages.success(request, 'Status updated successfully.')
        else:

QueryManager/main/templates/edit_query.html
{% load static %}
{% if user == quest.user or user.is_superuser %}
<a href="#" class="p-2 badge badge-dark" data-toggle="modal" data-target="#EditModalScrollable">
    Edit
    <i class="fa-solid fa-pen"></i>
</a>
{% endif %}

<!-- Edit Modal -->
<div class="modal fade" id="EditModalScrollable" tabindex="-1" role="dialog" aria-labelledby="EditModalScrollableTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="EditModalScrollableTitle"><i class="fa-regular fa-pen-to-square"></i> Edit your query</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        <div class="modal-body">
          <form method="post" enctype="multipart/form-data" action="{% url 'edit_query' quest.id %}">
                {% csrf_token %}
                    <!-- Display Existing Attachments -->
                    <div class="form-group">
                        <label><i class="fa-solid fa-paperclip"></i> Current attachments:</label>
                        <div id="existing-attachments-{{ quest.id }}">
                            <!-- File Attachments (Top) -->
                            <div class="attachment-files">
                                {% for attachment in quest.attachments.all %}
                                    {% if not attachment.is_image %}
                                        <div class="attachment-box">
                                            <a href="{{ attachment.file.url }}" target="_blank" class="file-link">{{ attachment.file.name }}</a>
                                            <i class="fa-solid fa-circle-xmark remove-attachment text-dark" 
                                            data-attachment-id="{{ attachment.id }}" 
                                            data-attachment-type="question"></i>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>

                            <!-- Image Attachments (Bottom) -->
                            <div class="attachment-images">
                                {% if attachment.is_image %}
                                    <a href="{{ attachment.file.url }}" class="glightbox" data-glightbox="gallery{{ answer.id }}">
                                        <img src="{{ attachment.file.url }}" alt="Image Attachment" class="img-fluid m-1" style="height: 200px; max-width: 300px;">
                                    </a>
                                {% endif %}

                                {% for attachment in quest.attachments.all %}
                                    {% if attachment.is_image %}
                                        <div class="attachment-box">
                                            <a href="{{ attachment.file.url }}" class="glightbox" data-glightbox="gallery{{ quest.id }}">
                                                <img src="{{ attachment.file.url }}" class="small-image">
                                            </a>    
                                                <i class="fa-solid fa-circle-xmark remove-attachment text-dark" 
                                                data-attachment-id="{{ attachment.id }}" 
                                                data-attachment-type="question"></i>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    
                    <div class="q-form-group form-group">
                        <label for="id_category">Category*</label>
                        <select name="category" class="form-control" id="id_category" required>
                            <!-- Automated only 16/4/25 -->
                            <option value="HotDocs" {% if quest.category == "HotDocs" %}selected{% endif %}>HotDocs</option>
                            <option value="Document Drafter" {% if quest.category == "Document Drafter" %}selected{% endif %}>Document Drafter</option>
                            <!-- Automated end -->
                            <!-- Major works only 16/4/25 -->
                            <option value="Formatting" {% if quest.category == "Formatting" %}selected{% endif %}>Formatting</option>
                            <option value="Editing" {% if quest.category == "Editing" %}selected{% endif %}>Editing</option>
                            <option value="Conversion" {% if quest.category == "Conversion" %}selected{% endif %}>Conversion</option>
                            <!-- Major works end -->
                        </select>
                    </div>
                    <div class="q-form-group form-group">
                        <label for="id_tags">Tags
                            <i class="fas fa-info-circle" data-toggle="tooltip" data-placement="right" title="This will be served as a keyword"></i>
                        </label>
                        <input type="text" id="id_tags_input" class="form-control" placeholder="Add tags and press Enter or use a comma">
                        <div id="tag-suggestions" class="suggestions-box"></div>
                        <div id="tags-container" class="mt-2">
                            {% for tag in quest.tags.all %}
                                <div class="tag badge badge-primary mr-2 mb-2 p-2" style="font-size: 16px;">
                                    {{ tag.name }}
                                    <span class="ml-2" style="cursor: pointer;" onclick="removeTag('{{ tag.name }}')">&times;</span>
                                </div>
                            {% endfor %}
                        </div>
                        <input type="hidden" id="id_tags" name="tags" value="{{ quest.tags.all|join:',' }}">
                    </div>
                    <div class="q-form-group form-group">
                    <label for="id_issue">Issue*</label>
                    <input type="text" class="form-control" id="id_issue" name="issue"
                        value="{{ quest.issue }}" placeholder="This will serve as a title" required>
                    </div>
                    <div class="q-form-group form-group">
                    <label for="id_detail">Detail</label>
                    <textarea class="form-control" id="id_detail" name="detail" rows="4">{{ quest.detail }}</textarea>
                    </div>
                    <div class="q-form-group form-group">
                    <label for="id_referenceform">Reference form*</label>
                    <input type="text" class="form-control" id="id_referenceform" name="referenceform"
                        value="{{ quest.referenceform }}" placeholder="e.g., LIT_123456">
                    </div>
                </div>
                <div class="modal-footer fixed-footer">
                    <div class="form-group w-100">
                        <label for="id_attachment">+<i class="fa-solid fa-paperclip"></i> Add new attachments: </label>
                        <input type="file" class="form-control-file" id="id_attachment" name="attachments" multiple>
                    </div>    
                <button type="submit" class="btn btn-dark w-100"><i class="fa-solid fa-floppy-disk"></i> Update Query</button>
                </div>
            </form>
        </div>
    </div>
</div>

QueryManager/main/templates/firstname_lastname.html
{% load static %}
{% if quest.user.first_name or quest.user.last_name %}
{{ quest.user.first_name }} {{ quest.user.last_name }}
{% else %}
{{ quest.user.username }}
{% endif %}

QueryManager/main/templates/pagination.html
{% load static %}
<nav class="my-3">
    <ul class="pagination justify-content-center">
      {% if quests.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?{% if request.GET.status %}status={{ request.GET.status }}&{% endif %}{% if request.GET.category %}category={{ request.GET.category }}&{% endif %}page={{ quests.previous_page_number }}">Previous</a>
        </li>
      {% endif %}
  
      {% for i in quests.paginator.page_range %}
        {% if i >= quests.number|add:-5 and i <= quests.number|add:5 %}
          <li class="page-item {% if quests.number == i %}active{% endif %}">
            <a class="page-link" href="?{% if request.GET.status %}status={{ request.GET.status }}&{% endif %}{% if request.GET.category %}category={{ request.GET.category }}&{% endif %}page={{ i }}">{{ i }}</a>
          </li>
        {% elif i == 1 or i == quests.paginator.num_pages %}
          <li class="page-item {% if quests.number == i %}active{% endif %}">
            <a class="page-link" href="?{% if request.GET.status %}status={{ request.GET.status }}&{% endif %}{% if request.GET.category %}category={{ request.GET.category }}&{% endif %}page={{ i }}">{{ i }}</a>
          </li>
        {% elif i == quests.number|add:-6 or i == quests.number|add:6 %}
          <li class="page-item disabled">
            <span class="page-link">...</span>
          </li>
        {% endif %}
      {% endfor %}
  
      {% if quests.has_next %}
        <li class="page-item">
          <a class="page-link" href="?{% if request.GET.status %}status={{ request.GET.status }}&{% endif %}{% if request.GET.category %}category={{ request.GET.category }}&{% endif %}page={{ quests.next_page_number }}">Next</a>
        </li>
      {% endif %}
    </ul>
</nav>

QueryManager/main/templates/post_query.html
{% load static %}
{% if user.is_authenticated %}
  <a class="text-reset text-decoration-none" href="#" data-toggle="modal" data-target="#ModalScrollable">
    <div class="card shadow-sm">
      <div class="card-body d-flex align-items-center">
        <img
          src="{% if user.profile_picture %}{{ user.profile_picture.url }}{% else %}{% static 'profile_pics/default2.jpg' %}{% endif %}"
          alt="Profile Picture" class="rounded-circle"
          style="width: 35px; height: 35px; margin-right: 10px;" />
        <span class="d-block border rounded p-2 w-100"><i class="fa-regular fa-pen-to-square"></i> Post your query, {{ user.get_username }}</span>
      </div>
    </div>
  </a>
{% else %}
  <a class="text-reset text-decoration-none" href="/QueryManager/accounts/login">
    <div class="card shadow-sm d-flex" style="background-color: #E5E8E9; height: 80px;">
      <p class="m-4">Login to post your query.</p>
    </div>
  </a>
{% endif %}

<!-- Modal -->
<div class="modal fade" id="ModalScrollable" tabindex="-1" role="dialog" aria-labelledby="ModalScrollableTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalScrollableTitle"><i class="fa-regular fa-pen-to-square"></i> Post your query, {{ user.get_username }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="q-form-group form-group">
            <label for="id_attachment">Attachment</label>
            <input type="file" class="form-control-file" id="id_attachment" name="attachments" multiple>
          </div>
          <!-- Changes 18/2/25 -->
          <div class="q-form-group form-group">
            <label for="id_category">Category*</label>
            <select name="category" class="form-control" id="id_category" required>
              <!-- Automated only -->
              <option value="HotDocs">HotDocs</option>
              <option value="Document Drafter">Document Drafter</option>
              <!-- Automated end -->
              <!-- Major works only 16/4/25 -->
              <option value="Formatting">Formatting</option>
              <option value="Editing">Editing</option>
              <option value="Conversion">Conversion</option>
              <!-- Major works -->
            </select>
          </div>
          <div class="q-form-group form-group">
            <label for="id_tags">Tags
                <i class="fas fa-info-circle" data-toggle="tooltip" data-placement="right" title="This will be served as a keyword"></i>
            </label>
            <input type="text" id="id_tags_input" class="form-control" placeholder="Add tags and press Enter or use a comma" onkeyup="showTagSuggestions(this.value)">
            <div id="tag-suggestions" class="suggestions-box"></div>
            <div id="tags-container" class="mt-2"></div>
            <input type="hidden" id="id_tags" name="tags">
          </div>
          <!-- Changes end -->
          <div class="q-form-group form-group">
            <label for="id_issue">Issue*</label>
            <input type="text" class="form-control" id="id_issue" name="issue"
              value="{{ form.issue.value|default_if_none:'' }}" placeholder="This will serve as a title" required>
          </div>
          <div class="q-form-group form-group">
            <label for="id_detail">Detail</label>
            <textarea class="form-control" id="id_detail" name="detail" rows="4">{{ form.detail.value|default_if_none:'' }}</textarea>
          </div>
          <div class="q-form-group form-group">
            <label for="id_referenceform">Reference Form*</label>
            <input type="text" class="form-control" id="id_referenceform" name="referenceform"
              value="{{ form.referenceform.value|default_if_none:'' }}" placeholder="e.g., LIT_123456" required>
          </div>
        </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary w-100">Post</button>
      </div>
      </form>
    </div>
  </div>
</div>